backend:
  name: github
  repo: qudlab/azbest-website
  branch: master

media_folder: "images"           # Where uploaded images go (in your repo)
public_folder: "/images"         # How those images are referenced in HTML

collections:
  - name: "products"
    label: "Watch Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Watch Name", name: "title", widget: "string" }
      - { label: "Price (₦)", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
